DATASET:
  num_class: 1
  root: "../../../introspective_ORB_SLAM/scripts/generated_training_data"
  raw_img_root: "../../../Jackal_Visual_Odom/sequences"
  raw_img_folder: "image_0"
  train_set: "train_jackal_t"
  validation_set: "valid_jackal_t"
  test_set: "test_jackal_t"
  use_color_images: False
  is_dataset_color: False
  session_prefix_len: 5
  normalize_input: True
  img_width: 512
  img_height: 512
  target_downsampling_rate: 8
  binarize_target: False

MODEL:
  is_regression_mode : True
  name: "ivslam_introspection_func"
  arch_encoder: "mobilenetv2dilated"
  arch_decoder: "c1_deepsup"
  fc_dim: 320
  predict_conf_mask: False

TRAIN:
  use_gpu : True
  batch_size_per_gpu: 1 # 5
  batch_size: 5
  workers : 2
  num_epoch: 200
  start_epoch: 0
  snapshot_interval : 1

  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  use_masked_loss: True


TEST:
  ground_truth_available : False
  save_raw_output: True
  output_img_width : 960
  output_img_height : 600
  test_model_encoder : "../../pretrained/ivslam_introspection_func/snapshots/ivslam_introspection_func_encoder_last_model_0004.pth"
  test_model_decoder : "../../pretrained/ivslam_introspection_func/snapshots/ivslam_introspection_func_decoder_last_model_0004.pth"
  use_gpu : True
  batch_size_per_gpu : 50
  batch_size: 5
  workers: 2
  result: ""

DIR: "../../pretrained"
